### ISSUE TITLE
tach check-external module names to distribution mapping fails

### ISSUE THREAD

**Issue by nischnei** [gauge-sh/tach#414] opened 2024-11-17 14:06 UTC
Hi,

I'd like to use tach to check if my pyproject.toml is complete and does not have unused dependencies.
However, the check-external fails for the following packages which have differing distribution and module names:

```
pillow
python-opencv
nuscenes-devkit
scikit_learn
```

It might be the issue of the packages not haveing the metadata properly defined, but then it would be nice to have an option to manually add a mapping. I want to use the check in a CI so it needs to succeed.

**Comment by emdoyle** [comment] 2024-11-19 01:31
Hi @nischnei ! Could you tell me the version of Python you are using, and whether these packages are installed into the environment in which `tach` is running? Hopefully a quick fix is to install them so that the metadata is found, but if the metadata is not being processed correctly I'll need to take a closer look.

And I think adding config for a manual mapping makes sense, I will add a task for this and ping back here when it is ready.

**Comment by nischnei** [comment] 2024-11-21 12:47
I am using Python 3.11, all packages are available in my conda environment where also tach is installed.

**Comment by emdoyle** [comment] 2024-11-26 06:27
While I couldn't reproduce locally, there is now  configuration available to explicitly remap these names:
https://docs.gauge.sh/usage/configuration#external

This is released in `0.15.4`, let me know if you hit any issues!

**Closed by emdoyle** 2024-11-26 06:27 UTC
